ceph: fix do_configure failure for multilib
Issue: LIN1018-125

Add '-D_FILE_OFFSET_BITS=64' to CFLAGS to fix the following do_configure
error.

  FATAL ERROR: cannot find a valid <xfs/xfs.h> header file.

Although -D_FILE_OFFSET_BITS=64 has already been defined in
src/Makefile-env.am, it only affects the compile process, leaving configure
process unaware of this value.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>