wrlinux-base-whitelist.inc: add ima-evm-utils
Issue: LIN1018-281

add ima-evm-utils to whitelist as ima-inspect
require it to fix below error:

ERROR: Nothing PROVIDES 'ima-evm-utils' (but
../layers/meta-secure-core/meta-integrity/recipes-support/ima-inspect/ima-inspect_0.11.bb
DEPENDS on or otherwise requires it)
ima-evm-utils was skipped: Not supported in this configuration by Wind
River.  To override, add to your local.conf: PNWHITELIST_integrity +=
'ima-evm-utils'
ERROR: Required build target 'meta-world-pkgdata' has no buildable
providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata',
'lib32-meta-world-pkgdata', 'ima-inspect', 'ima-evm-utils']

Signed-off-by: Mingli Yu <Mingli.Yu@windriver.com>