wrlinux: Add ipcalc and dbus-daemon-proxy
Issue: LINUXEXEC-30502 LINCD-16209

Fixes:
  ERROR: Required build target 'podman' has no buildable providers.
  Missing or unbuildable dependency chain was: ['podman', 'netavark', 'dbus-daemon-proxy']

  Missing or unbuildable dependency chain was: ['podman', 'netavark', 'aardvark-dns', 'ipcalc']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>