wrlinux-overc.conf: Disable overc.immutable temporarily
bitbake has updated siggen.py API, the overc.immutable caused errors like:
bb.warn('self.dataCaches: %s' % self.dataCaches[mc_from_tid(tid)])
>        self.runtaskentries[tid].hash = bb.parse.siggen.get_taskhash(tid, procdep, self.dataCaches[mc_from_tid(tid)])
self.runtaskentries[tid].unihash = bb.parse.siggen.get_unihash(tid)
TypeError: get_taskhash() missing 1 required positional argument: 'dataCache'

Tracked by LIN1019-2075.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>