wrlinux-overc: set INSTALL_BSP before sourcing config-usb.sh
Issue: LIN1019-2969

When attempting to build an installer image using the following (as
outlined in our documentation)

sudo PATH=$PWD/tmp/sysroots/x86_64/usr/bin:$PWD/tmp/sysroots/x86_64/usr/sbin:$PATH \
 ../overc-installer/sbin/cubeit --disk-size 15G --force \
 --target-config `pwd`/image-live.sh --installer \
 --config `pwd`/image-live.sh \
 --artifacts `pwd`/tmp/deploy/images/genericx86-64 boot.img

We see the following error
ERROR: Could not find necessary file: .../tmp/deploy/images/genericx86-64/cube-essential-.tar.bz2

When using '--installer --target-config' the installer checks for the
existence of PREREQ_FILES. PREREQ_FILES is set with the value of
INSTALL_ROOTFS which is being set with an empty INSTALL_BSP since we
haven't set it yet. To properly setup PREREQ_FILES we need to set
INSTALL_BSP and IMAGE_ROOTFS before sourcing config-usb.sh.

While we are at it why might as well expand PREREQ_FILES as the
meta-overc configurations usually do.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>