ovp: qemu: Remove dependency bluez
Issue: LIN1019-2286

ERROR: Nothing PROVIDES 'bluez4' (but qemu_4.0.0.bb DEPENDS on or otherwise requires it). Close matches:

bluez has been upgraded to bluez5 and the dependency on bluez has been covered
by oe-core. So remove it from ovp.

Signed-off-by: He Zhe <zhe.he@windriver.com>