conf/wrlinux-blacklist.conf: remove consul from RDEPENDS
It had been blacklisted.

Workaround for overc:
ERROR: Required build target 'cube-dom0' has no buildable providers.
Missing or unbuildable dependency chain was: ['cube-dom0', 'packagegroup-service-discovery', 'consul']

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>