grub_2.02.bbappend: Remove it temporarily
It caused errors like:
ERROR: No recipes available for:
/home/wrlbuild/builds/builds-73b34ba4-a2cd-4f5d-bb4b-c56815502a4f/layers/wrlinux/recipes-bsp/grub/grub_2.02.bbappend

Tracked by LIN1019-2064.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>