wrlinux-uninative.inc: require yocto-uninative.inc
Issue: US110920

UNINATIVE_MAXGLIBCVERSION = "2.27" is added in oe-core by:
"""
commit d6f6101cd0ae92e8ad2dec0bcb6db5044726edf9
Author: Richard Purdie <richard.purdie@linuxfoundation.org>
Date:   Wed Mar 14 09:52:18 2018 -0700

    uninative: Add compatiblity version check

    If glibc is newer on the host than in uninative, the failure mode is
    pretty nasty for clusters where the sstate is shared, including the Yocto
    Project autobuilder.

    This check aborts the use of uninative in such scenarios where a newer
    glibc version appears and avoids corruption of sstate caches.

    We use ldd to check the glibc version since that is included in libc-bin
    (or equivalent) which locales use so it should always be present.

    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
"""

So require yocto-uninative.inc to include the definition of
UNINATIVE_MAXGLIBCVERSION to avoid issue:
| ERROR: Execution of event handler 'uninative_event_fetchloader' failed
| AttributeError: 'NoneType' object has no attribute 'strip'

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>