wrlinux-std-sato.conf: Move polkit to wrlinux.conf
Issue: US131069

Otherwise, the world build doesn't work for distro wrlinux and wrlinux-small.

Fixed:
DISTRO = "wrlinux-small"
$ bitbake world
ERROR: Nothing PROVIDES 'polkit' (but /path/to/layers/meta-openembedded/meta-oe/recipes-support/udisk
s/udisks2_2.7.8.bb, /path/to/layers/meta-openembedded/meta-oe/recipes-support/upower/upower_0.99.7.bb DEPENDS on or otherwise requires it)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>