recipelists.bbclass: replace dropped bb.cache.parse_recipe call
Issue: LINCD-11701

The bb.cache.parse_recipe call has been dropped and we need to
replace it, otherwise we get the following error:

  reciplists.bbclass not working: module 'bb.cache' has no attribute 'parse_recipe'

There's no direct replacement, so we need to use its original
internal implementation to replace it.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>