packagegroup-zabbix-monitoring: Only use one package.
Issue: LIN1018-2253

Fixed:

$ bitbake packagegroup-zabbix-monitoring
[snip]
ERROR: Nothing RPROVIDES 'zabbix-agent'
[snip]

This because now we use zabbix from meta-oe which don't have
zabbix-agent or others, it packs the files into a single binary
package zabbix.

Remove workaround from conf/wrlinux-blacklist.conf

Signed-off-by: Hongzhi.Song <hongzhi.song@windriver.com>