Revert "recipelists.bbclass: Use event RecipePreFinalise to skip unsupported recipes earlier"
Caused errors like:
ERROR: Nothing RPROVIDES 'nativesdk-python3-django'

This reverts commit 8128ff71f8e80a30c1506628f0ab769f892c465e.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>