conf/wrlinux-recipeskip.conf: add back gtkmm4 setting
Issue: LINUXEXEC-33207
Issue: LIN1024-5066

gtkmm4 needs to be here, otherwise, we'll see the following error:

  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'gtkmm4', 'cairomm-1.16']

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>