feature/cut: whitelist cmocka
Issue: LINCD-9077

Cmocka is required by libyang when enable ptest feature.

Fix build error when enable template cut:
ERROR: Nothing PROVIDES 'cmocka' (but libyang_2.0.164.bb DEPENDS on or otherwise requires it)
ERROR: Required build target 'wrlinux-image-cgl' has no buildable providers.
Missing or unbuildable dependency chain was: ['wrlinux-image-cgl', 'packagegroup-wr-core-cgl', 'frr', 'libyang', 'cmocka']

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>