wrlinux-recipelists.conf: add ti-hsm-demo-fw to WRL_RECIPES:meta-ti-bsp
Issue: LIN1024-9544

In commit 1594a368 ("ti-hsm-demo-fw: Add a recipe to export prebuilt HSM
demo firmware") of meta-ti, the package "ti-hsm-demo-fw" is added to the
DEPENDS of "u-boot-ti-staging", so we need to add "ti-hsm-demo-fw" to
WRL_RECIPES:meta-ti-bsp to fix the following error:

ERROR: Nothing PROVIDES 'ti-hsm-demo-fw' (but meta-ti/meta-ti-bsp/recipes-bsp/u-boot/u-boot-ti-staging_2024.04.bb DEPENDS on or otherwise requires it)
ti-hsm-demo-fw was skipped: You are about to enable third-party components, there is additional third-part licensing involved, please consult your legal department should you have questions regarding the licensing terms and obligations.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>