buildtools-tarball: Add nativesdk-python3-jinja2
Issue: LINCD-883

It is required by ptest:
File "/path/to/layers/oe-core/scripts/lib/resulttool/report.py", line 162, in print_test_report
from jinja2 import Environment, FileSystemLoader
ModuleNotFoundError: No module named 'jinja2'

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>