monit 4.9: fix compile failure since openssl upgraded to 1.1.1
Issue: LIN1018-2291

Since openssl upgraded to 1.1.1, there is a compile failure
[snip]
|ssl.c:822:15: error: storage size of 'found_cert' isn't known
|   X509_OBJECT found_cert;
|               ^~~~~~~~~~
|ssl.c:824:46: error: dereferencing pointer to incomplete type
'X509_STORE_CTX' {aka 'struct x509_store_ctx_st'}
|   X509_NAME_oneline(X509_get_subject_name(ctx->current_cert), subject,
[snip]

Refer above commits to tweak ssl reference.

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>