feature/chromium: explicitly disable optimize webui
There is an occasionally failure while optimizing webui in which
it calls node js broken
[snip]
[11084/48229] python ../../chrome/browser/resources/optimize_webui.py --host print --input gen/chrome/browser/resources/print_preview/preprocessed --out_folder
gen/chrome/browser/resources/print_preview --depfile gen/chrome/browser/resources/print_preview/build.d --js_out_files print_preview.rollup.js --exclude chrome://resources/js/cr.m.js
pdf/pdf_scripting_api.js --js_module_in_files print_preview.js
FAILED: gen/chrome/browser/resources/print_preview/print_preview.rollup.js
...
RuntimeError: ['../../third_party/node/linux/node-linux-x64/bin/node', '../../third_party/node/node_modules/polymer-css-build/bin/polymer-css-build', '--polymer-version', '2', '--no-inline-includes',
'-f', 'TOPDIR/tmp-glibc/work/cortexa72-wrs-linux/chromium-x11/87.0.4280.141-r0/chromium-87.0.4280.141/out/Release/gen/chrome/browser/resources/print_preview/tmpRsijqF/print_preview.rollup.js', '-o',
'TOPDIR/tmp-glibc/work/cortexa72-wrs-linux/chromium-x11/87.0.4280.141-r0/chromium-87.0.4280.141/out/Release/gen/chrome/browser/resources/print_preview/tmpRsijqF/print_preview.rollup.js'] failed:
TypeError: Cannot convert name to ASCII
[snip]

Since all of generated js are not installed to ${D}, explicitly disable
optimize webui does not have any side effect for target chromium

BTW: Ubuntu has disabled optimize webui in its chromium build too

Issue: LINCD-3689

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>