packagegroup-wr-core-cgl: remove eventlog
Issue: LIN1018-2474

* Remove eventlog from packagegroup-wr-core-cgl
  as there is no dependency for eventlog in
  glibc-cgl and altogether to fix below error:
  Error: Transaction check error:
  file /usr/lib64/libevtlog.so conflicts between attempted installs of libevtlog-dev-0.2.13+git0+a5c19163ba-r0.corei7_64 and syslog-ng-dev-3.16.1-r0.corei7_64

* Per below commit, eventlog is introduced as
  syslog-ng depends on it.

  eventlog: move to wr-features because of syslog-ng

  CQID: WIND00408497

  The syslog-ng recipe, located in the wr-features
  layer requires the "eventlog" recipe.
  Currently the eventlog recipe is only provided
  as part of the CGP layer. By moving eventlog back
  to wr-features, it will enable syslog-ng to be built
  for configurations that don't include the CGP layer.

  Signed-off-by: Aws Ismail <aws.ismail@windriver.com>
  Signed-off-by: Mark Hatle <mark.hatle@windriver.com>

* But eventlog is not external lib anymore and it
  has been already integrated to syslog-ng.

  syslog-ng: update to 3.15.1

  - Refresh and remove obsolete patches
    - Fix PAGESIZE variable conflicting
      - PAGESIZE is a define in some libc libraries
    - Implement SystemD service files handling
      - splitted service into default
    - Remove dependency to eventlog
      - external libevtlog library linking was removed
    - Version 3.15.1 supports OpenSSL 1.1

   Signed-off-by: Andrej Valek <andrej.valek@siemens.com>
   Signed-off-by: Marko Pater <peter.marko@siemens.com>
   Signed-off-by: Khem Raj <raj.khem@gmail.com>

Reference:
http://lxgit.wrs.com/cgit/layers/wr-cgl/commit/?h=WRLINUX_7_0_HEAD&id=5b7ea50e93efa311fbb1dca671d1a341efef6761
http://lxgit.wrs.com/cgit/layers/meta-openembedded/commit/?h=wr-10.18-20180918&id=0ce7d3d0413559d9a41027273cb4bccaefd6ba73

Signed-off-by: Mingli Yu <Mingli.Yu@windriver.com>