conf/layer.conf: set BBLAYERS_LAYERINDEX_URL to wrlinux layerindex
Issue: LINCD-5821

Newly add oe-selftest case BitbakeLayers test_bitbakelayers_layerindexshowdepends
failed because BBLAYERS_LAYERINDEX_URL is set to oe's layerindex, but
bitbake layer have some wrlinux specific code

File "/layers/oe-core/bitbake/lib/layerindexlib/restapi.py", line 261, in load_index_web
    logger.debug("Loading %s from %s" % (lName, index.apilinks[lName]))
KeyError: 'wrtemplates'

Signed-off-by: Changqing Li <changqing.li@windriver.com>