wrlinux-whitelist.conf: Add numactl from cgl and ovp
Issue: LIN1019-814

The numactl is required by cgl, ovp and overc, so add it to wrlinux-whitelist.conf.

Fixed when overc building:
ERROR: Nothing PROVIDES 'numactl'

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>