qtbase: install sqlite plugin for qt-example
Issue: LIN1024-694

The sqlite plugin is required by localstorageexample
```
$ /usr/share/examples/quick/localstorage/localstorageexample
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, but has failed to switch to one.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
QSqlQuery::prepare: database not open
qml: Error creating table in database: Error: Driver not loaded Driver not loaded
QSqlQuery::prepare: database not open
qrc:/qt/qml/localstorage/Database.js:44: Error: Driver not loaded Driver not loaded
```
wrlinux using feature to contorl the qt examples, so add the sqlite
plugin default when enable the qt-example.

Signed-off-by: Zhang Peng <peng.zhang1.cn@windriver.com>