conf/gen-vendor-revision.conf: Workaround ExpansionError during parsing recipes for XILINX
These variables were set with bsp specific overrides and do not have
default value which made ExpansionError for other bsp (intel-x86-64)

Such as:
```
ERROR: ExpansionError during parsing meta-xilinx/meta-xilinx-core/recipes-bsp/u-boot/u-boot-xlnx-uenv.bb          | ETA:  0:01:28
Traceback (most recent call last):
  File "Var <DEVICETREE_OVERLAY_LOAD_ADDRESS>", line 1, in <module>
bb.data_smart.ExpansionError: Failure expanding variable DEVICETREE_OVERLAY_LOAD_ADDRESS, expression was ${@hex(int(d.getVar("DEVICETREE_LOAD_ADDRESS"),16) + 0xf00000)} which triggered exception TypeError: int() can't convert non-string with explicit base
The variable dependency chain for the failure is: DEVICETREE_OVERLAY_LOAD_ADDRESS
```

Issue: LIN1024-3090

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>