wrlinux/dpdk: define variable BSP_NXP_DERIVED explicitly
Issue: LINUXEXEC-31387

When building lts24 BSP with template dpdk, there is below error:
ERROR: Nothing RPROVIDES ''dpdk-examples','
ERROR: Required build target 'wrlinux-image-std' has no buildable providers.
The root cause  is that contains_any() doesn’t work correctly if passing an
undefine variable to it. So, define BSP_NXP_DERIVED explicitly to avoid building
issue.

Signed-off-by: Meng Li <Meng.Li@windriver.com>