busybox_1.27.2.bbappend: Remove it temporarily
It caused error when distro is not wrlinux:
 ERROR: No recipes available for:
   /path/to/layers/wrlinux/recipes-core/busybox/busybox_1.27.2.bbappend

Tracked by LIN1018-2290

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>