packagefeed-stability.bbclass: Depends gcc-cross conditionally
Issue: LINUXEXEC-22308

Only depends on gcc-cross when it is not a targer recipe and not set
INHIBIT_DEFAULT_DEPS.

Fixed when MACHINE = "bcm-2xxx-rpi4":
$ bitbake wrlinux-image-minimal
ERROR: Nothing PROVIDES 'gcc-cross-x86_64'. Close matches:

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>