gen-image: Create the directory when prepare upload dir
Issue: LINCD-3823

The directory outdir/upload/latest/WRLinux-CD-Images/bcm-2xxx-rpi4 would be a
file when use shutil.copy() to copy a file to it, and caused errors like:

NotADirectoryError: [Errno 20] Not a directory: '/path/to/outdir/upload/2021-01-14/WRLinux-CD-Images/bcm-2xxx-rpi4/repos'

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>